import "dotenv/config";

const DEFAULT_CONFIG = {
  CLICKHOUSE_HOST: "http://localhost:8123",
  CLICKHOUSE_DATABASE: "default",
  CLICKHOUSE_USER: "default",
  CLICKHOUSE_PASSWORD: "default",
  CLICKHOUSE_TICKS_TABLE: "ticks",
  CLICKHOUSE_MARKET_REGISTRY_TABLE: "market_registry",
  CLICKHOUSE_ASYNC_INSERT: 1,
  CLICKHOUSE_WAIT_FOR_ASYNC_INSERT: 0,
  INGEST_BATCH_SIZE: 1_000,
  INGEST_FLUSH_INTERVAL_MS: 2_000,
  INGEST_COALESCE_WINDOW_MS: 500,
  INGEST_COALESCE_CLEANUP_INTERVAL_MS: 60_000,
  INGEST_COALESCE_KEY_TTL_MS: 3_600_000,
  ORDERBOOK_MAX_LEVELS: 5,
  TICKS_TTL_DAYS: 90,
  POLYMARKET_DISCOVERY_INTERVAL_MS: 30_000,
  PRICE_TO_BEAT_POLL_INTERVAL_MS: 10_000,
  PRICE_TO_BEAT_STARTUP_BACKFILL_ENABLED: 1,
  PRICE_TO_BEAT_STARTUP_BACKFILL_LIMIT: 500,
  PRICE_TO_BEAT_STARTUP_BACKFILL_DELAY_MS: 2_000,
  PRICE_TO_BEAT_API_BASE_URL: "https://polymarket.com/api/crypto/crypto-price",
  SUPPORTED_ASSETS: ["btc", "eth", "sol", "xrp"],
  SUPPORTED_WINDOWS: ["5m", "15m"],
  CRYPTO_PROVIDERS: ["binance", "coinbase", "kraken", "okx", "chainlink"]
} as const;

const TEST_CLICKHOUSE_DEFAULTS = { CLICKHOUSE_HOST: "http://192.168.1.2:8123", CLICKHOUSE_USER: "default", CLICKHOUSE_PASSWORD: "default" } as const;

function resolveClickHouseHostFallback(): string {
  const fallback = process.env.NODE_ENV === "test" ? TEST_CLICKHOUSE_DEFAULTS.CLICKHOUSE_HOST : DEFAULT_CONFIG.CLICKHOUSE_HOST;
  return fallback;
}

function resolveClickHouseUserFallback(): string {
  const fallback = process.env.NODE_ENV === "test" ? TEST_CLICKHOUSE_DEFAULTS.CLICKHOUSE_USER : DEFAULT_CONFIG.CLICKHOUSE_USER;
  return fallback;
}

function resolveClickHousePasswordFallback(): string {
  const fallback = process.env.NODE_ENV === "test" ? TEST_CLICKHOUSE_DEFAULTS.CLICKHOUSE_PASSWORD : DEFAULT_CONFIG.CLICKHOUSE_PASSWORD;
  return fallback;
}

function readStringEnv(key: string, fallback: string): string {
  const rawValue = process.env[key];
  let resolvedValue = fallback;

  if (typeof rawValue === "string") {
    const trimmedValue = rawValue.trim();

    if (trimmedValue.length > 0) {
      resolvedValue = trimmedValue;
    }
  }

  return resolvedValue;
}

function readIntegerEnv(key: string, fallback: number): number {
  const rawValue = process.env[key];
  let resolvedValue = fallback;

  if (typeof rawValue === "string") {
    const parsedValue = Number.parseInt(rawValue, 10);

    if (Number.isFinite(parsedValue)) {
      resolvedValue = parsedValue;
    }
  }

  return resolvedValue;
}

function readBooleanIntegerEnv(key: string, fallback: 0 | 1): 0 | 1 {
  const parsedValue = readIntegerEnv(key, fallback);
  const resolvedValue: 0 | 1 = parsedValue === 1 ? 1 : 0;
  return resolvedValue;
}

const CONFIG = {
  CLICKHOUSE_HOST: readStringEnv("CLICKHOUSE_HOST", resolveClickHouseHostFallback()),
  CLICKHOUSE_DATABASE: readStringEnv("CLICKHOUSE_DATABASE", DEFAULT_CONFIG.CLICKHOUSE_DATABASE),
  CLICKHOUSE_USER: readStringEnv("CLICKHOUSE_USER", resolveClickHouseUserFallback()),
  CLICKHOUSE_PASSWORD: readStringEnv("CLICKHOUSE_PASSWORD", resolveClickHousePasswordFallback()),
  CLICKHOUSE_TICKS_TABLE: readStringEnv("CLICKHOUSE_TICKS_TABLE", DEFAULT_CONFIG.CLICKHOUSE_TICKS_TABLE),
  CLICKHOUSE_MARKET_REGISTRY_TABLE: readStringEnv("CLICKHOUSE_MARKET_REGISTRY_TABLE", DEFAULT_CONFIG.CLICKHOUSE_MARKET_REGISTRY_TABLE),
  CLICKHOUSE_ASYNC_INSERT: readBooleanIntegerEnv("CLICKHOUSE_ASYNC_INSERT", DEFAULT_CONFIG.CLICKHOUSE_ASYNC_INSERT),
  CLICKHOUSE_WAIT_FOR_ASYNC_INSERT: readBooleanIntegerEnv("CLICKHOUSE_WAIT_FOR_ASYNC_INSERT", DEFAULT_CONFIG.CLICKHOUSE_WAIT_FOR_ASYNC_INSERT),
  INGEST_BATCH_SIZE: readIntegerEnv("INGEST_BATCH_SIZE", DEFAULT_CONFIG.INGEST_BATCH_SIZE),
  INGEST_FLUSH_INTERVAL_MS: readIntegerEnv("INGEST_FLUSH_INTERVAL_MS", DEFAULT_CONFIG.INGEST_FLUSH_INTERVAL_MS),
  INGEST_COALESCE_WINDOW_MS: readIntegerEnv("INGEST_COALESCE_WINDOW_MS", DEFAULT_CONFIG.INGEST_COALESCE_WINDOW_MS),
  INGEST_COALESCE_CLEANUP_INTERVAL_MS: readIntegerEnv("INGEST_COALESCE_CLEANUP_INTERVAL_MS", DEFAULT_CONFIG.INGEST_COALESCE_CLEANUP_INTERVAL_MS),
  INGEST_COALESCE_KEY_TTL_MS: readIntegerEnv("INGEST_COALESCE_KEY_TTL_MS", DEFAULT_CONFIG.INGEST_COALESCE_KEY_TTL_MS),
  ORDERBOOK_MAX_LEVELS: readIntegerEnv("ORDERBOOK_MAX_LEVELS", DEFAULT_CONFIG.ORDERBOOK_MAX_LEVELS),
  TICKS_TTL_DAYS: readIntegerEnv("TICKS_TTL_DAYS", DEFAULT_CONFIG.TICKS_TTL_DAYS),
  POLYMARKET_DISCOVERY_INTERVAL_MS: readIntegerEnv("POLYMARKET_DISCOVERY_INTERVAL_MS", DEFAULT_CONFIG.POLYMARKET_DISCOVERY_INTERVAL_MS),
  PRICE_TO_BEAT_POLL_INTERVAL_MS: readIntegerEnv("PRICE_TO_BEAT_POLL_INTERVAL_MS", DEFAULT_CONFIG.PRICE_TO_BEAT_POLL_INTERVAL_MS),
  PRICE_TO_BEAT_STARTUP_BACKFILL_ENABLED: readBooleanIntegerEnv(
    "PRICE_TO_BEAT_STARTUP_BACKFILL_ENABLED",
    DEFAULT_CONFIG.PRICE_TO_BEAT_STARTUP_BACKFILL_ENABLED
  ),
  PRICE_TO_BEAT_STARTUP_BACKFILL_LIMIT: readIntegerEnv("PRICE_TO_BEAT_STARTUP_BACKFILL_LIMIT", DEFAULT_CONFIG.PRICE_TO_BEAT_STARTUP_BACKFILL_LIMIT),
  PRICE_TO_BEAT_STARTUP_BACKFILL_DELAY_MS: readIntegerEnv("PRICE_TO_BEAT_STARTUP_BACKFILL_DELAY_MS", DEFAULT_CONFIG.PRICE_TO_BEAT_STARTUP_BACKFILL_DELAY_MS),
  PRICE_TO_BEAT_API_BASE_URL: readStringEnv("PRICE_TO_BEAT_API_BASE_URL", DEFAULT_CONFIG.PRICE_TO_BEAT_API_BASE_URL),
  SUPPORTED_ASSETS: DEFAULT_CONFIG.SUPPORTED_ASSETS,
  SUPPORTED_WINDOWS: DEFAULT_CONFIG.SUPPORTED_WINDOWS,
  CRYPTO_PROVIDERS: DEFAULT_CONFIG.CRYPTO_PROVIDERS
} as const;

export default CONFIG;
